# -*- coding: utf-8 -*-
# Generated by Django 1.9.7 on 2016-06-24 11:52
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_auto_20160624_1334'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmark',
            name='created',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
