# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-04-18 11:27
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_postmark_session_key'),
    ]

    operations = [
        migrations.AlterField(
            model_name='postmark',
            name='user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
